/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipamentosRouteImport } from './routes/equipamentos'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RegioesRouteImport } from './routes/regioes'
import { Route as RoteirizacaoRouteImport } from './routes/roteirizacao'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as RotaCodigoRouteImport } from './routes/rota.$codigo'
import { Route as SimuladorIndexRouteImport } from './routes/simulador.index'
import { Route as SimuladorCodigoRouteImport } from './routes/simulador.$codigo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosRoute = EquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RegioesRoute = RegioesRouteImport.update({
  id: '/regioes',
  path: '/regioes',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteirizacaoRoute = RoteirizacaoRouteImport.update({
  id: '/roteirizacao',
  path: '/roteirizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const RotaCodigoRoute = RotaCodigoRouteImport.update({
  id: '/rota/$codigo',
  path: '/rota/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorIndexRoute = SimuladorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SimuladorRoute,
} as any)
const SimuladorCodigoRoute = SimuladorCodigoRouteImport.update({
  id: '/$codigo',
  path: '/$codigo',
  getParentRoute: () => SimuladorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipamentos': typeof EquipamentosRoute
  '/ranking': typeof RankingRoute
  '/regioes': typeof RegioesRoute
  '/roteirizacao': typeof RoteirizacaoRoute
  '/simulador': typeof SimuladorRouteWithChildren
  '/rota/$codigo': typeof RotaCodigoRoute
  '/simulador/$codigo': typeof SimuladorCodigoRoute
  '/simulador/': typeof SimuladorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipamentos': typeof EquipamentosRoute
  '/ranking': typeof RankingRoute
  '/regioes': typeof RegioesRoute
  '/roteirizacao': typeof RoteirizacaoRoute
  '/rota/$codigo': typeof RotaCodigoRoute
  '/simulador/$codigo': typeof SimuladorCodigoRoute
  '/simulador': typeof SimuladorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipamentos': typeof EquipamentosRoute
  '/ranking': typeof RankingRoute
  '/regioes': typeof RegioesRoute
  '/roteirizacao': typeof RoteirizacaoRoute
  '/simulador': typeof SimuladorRouteWithChildren
  '/rota/$codigo': typeof RotaCodigoRoute
  '/simulador/$codigo': typeof SimuladorCodigoRoute
  '/simulador/': typeof SimuladorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/equipamentos'
    | '/ranking'
    | '/regioes'
    | '/roteirizacao'
    | '/simulador'
    | '/rota/$codigo'
    | '/simulador/$codigo'
    | '/simulador/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/equipamentos'
    | '/ranking'
    | '/regioes'
    | '/roteirizacao'
    | '/rota/$codigo'
    | '/simulador/$codigo'
    | '/simulador'
  id:
    | '__root__'
    | '/'
    | '/equipamentos'
    | '/ranking'
    | '/regioes'
    | '/roteirizacao'
    | '/simulador'
    | '/rota/$codigo'
    | '/simulador/$codigo'
    | '/simulador/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipamentosRoute: typeof EquipamentosRoute
  RankingRoute: typeof RankingRoute
  RegioesRoute: typeof RegioesRoute
  RoteirizacaoRoute: typeof RoteirizacaoRoute
  SimuladorRoute: typeof SimuladorRouteWithChildren
  RotaCodigoRoute: typeof RotaCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos': {
      id: '/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof EquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regioes': {
      id: '/regioes'
      path: '/regioes'
      fullPath: '/regioes'
      preLoaderRoute: typeof RegioesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteirizacao': {
      id: '/roteirizacao'
      path: '/roteirizacao'
      fullPath: '/roteirizacao'
      preLoaderRoute: typeof RoteirizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rota/$codigo': {
      id: '/rota/$codigo'
      path: '/rota/$codigo'
      fullPath: '/rota/$codigo'
      preLoaderRoute: typeof RotaCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador/': {
      id: '/simulador/'
      path: '/'
      fullPath: '/simulador/'
      preLoaderRoute: typeof SimuladorIndexRouteImport
      parentRoute: typeof SimuladorRoute
    }
    '/simulador/$codigo': {
      id: '/simulador/$codigo'
      path: '/$codigo'
      fullPath: '/simulador/$codigo'
      preLoaderRoute: typeof SimuladorCodigoRouteImport
      parentRoute: typeof SimuladorRoute
    }
  }
}

interface SimuladorRouteChildren {
  SimuladorCodigoRoute: typeof SimuladorCodigoRoute
  SimuladorIndexRoute: typeof SimuladorIndexRoute
}

const SimuladorRouteChildren: SimuladorRouteChildren = {
  SimuladorCodigoRoute: SimuladorCodigoRoute,
  SimuladorIndexRoute: SimuladorIndexRoute,
}

const SimuladorRouteWithChildren = SimuladorRoute._addFileChildren(
  SimuladorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipamentosRoute: EquipamentosRoute,
  RankingRoute: RankingRoute,
  RegioesRoute: RegioesRoute,
  RoteirizacaoRoute: RoteirizacaoRoute,
  SimuladorRoute: SimuladorRouteWithChildren,
  RotaCodigoRoute: RotaCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
