/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RoteirizacaoRouteImport } from './routes/roteirizacao'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as RotaCodigoRouteImport } from './routes/rota.$codigo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteirizacaoRoute = RoteirizacaoRouteImport.update({
  id: '/roteirizacao',
  path: '/roteirizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const RotaCodigoRoute = RotaCodigoRouteImport.update({
  id: '/rota/$codigo',
  path: '/rota/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ranking': typeof RankingRoute
  '/roteirizacao': typeof RoteirizacaoRoute
  '/simulador': typeof SimuladorRoute
  '/rota/$codigo': typeof RotaCodigoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ranking': typeof RankingRoute
  '/roteirizacao': typeof RoteirizacaoRoute
  '/simulador': typeof SimuladorRoute
  '/rota/$codigo': typeof RotaCodigoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ranking': typeof RankingRoute
  '/roteirizacao': typeof RoteirizacaoRoute
  '/simulador': typeof SimuladorRoute
  '/rota/$codigo': typeof RotaCodigoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ranking' | '/roteirizacao' | '/simulador' | '/rota/$codigo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ranking' | '/roteirizacao' | '/simulador' | '/rota/$codigo'
  id:
    | '__root__'
    | '/'
    | '/ranking'
    | '/roteirizacao'
    | '/simulador'
    | '/rota/$codigo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RankingRoute: typeof RankingRoute
  RoteirizacaoRoute: typeof RoteirizacaoRoute
  SimuladorRoute: typeof SimuladorRoute
  RotaCodigoRoute: typeof RotaCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteirizacao': {
      id: '/roteirizacao'
      path: '/roteirizacao'
      fullPath: '/roteirizacao'
      preLoaderRoute: typeof RoteirizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rota/$codigo': {
      id: '/rota/$codigo'
      path: '/rota/$codigo'
      fullPath: '/rota/$codigo'
      preLoaderRoute: typeof RotaCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RankingRoute: RankingRoute,
  RoteirizacaoRoute: RoteirizacaoRoute,
  SimuladorRoute: SimuladorRoute,
  RotaCodigoRoute: RotaCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
