/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RoteirizacaoRouteImport } from './routes/roteirizacao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteirizacaoRoute = RoteirizacaoRouteImport.update({
  id: '/roteirizacao',
  path: '/roteirizacao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ranking': typeof RankingRoute
  '/roteirizacao': typeof RoteirizacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ranking': typeof RankingRoute
  '/roteirizacao': typeof RoteirizacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ranking': typeof RankingRoute
  '/roteirizacao': typeof RoteirizacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ranking' | '/roteirizacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ranking' | '/roteirizacao'
  id: '__root__' | '/' | '/ranking' | '/roteirizacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RankingRoute: typeof RankingRoute
  RoteirizacaoRoute: typeof RoteirizacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteirizacao': {
      id: '/roteirizacao'
      path: '/roteirizacao'
      fullPath: '/roteirizacao'
      preLoaderRoute: typeof RoteirizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RankingRoute: RankingRoute,
  RoteirizacaoRoute: RoteirizacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
